default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", nil) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV", "sample_app_again_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "sample_app_again_test") %>

production:
  <<: *default
  database: <%= ENV["DB_NAME_PROD"] %>
  username: <%= ENV["DB_USERNAME_PROD"] %>
  password: <%= ENV["DB_PASSWORD_PROD"] %>
  host: <%= ENV.fetch("DB_HOST_PROD", "127.0.0.1") %>
